version: '3.2'
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      hostname: changedetection
      volumes:
        - ./changedetection-data:/datastore
      ports:
        - ${SERVICE_PORT}:5000
      restart: unless-stopped
