version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${SERVICE_PORT}:5432"
    restart: unless-stopped

volumes:
    postgres:
