version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - KEYBOARD=en-us-qwerty #optional
      - TITLE=Webtop #optional
    volumes:
      - ${PATH_TO_DATA}:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - ${SERVICE_PORT}:3000
    # devices:
    #   - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
