version: "2.3"
services:
  emby:
    image: emby/embyserver_arm64v8:latest
    container_name: embyserver
    #network_mode: host # Enable DLNA and Wake-on-Lan Linux ONLY
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - ./config:/config # Configuration directory
      - ./media:/mnt/share1 # Media directory
    ports:
      - ${SERVICE_PORT}:8096 # HTTP port
    restart: unless-stopped
