version: '3'

services:

  docker-fastapi:
   container_name: docker-fastapi
   image: ghcr.io/wmramadan/fastapi-boilerplate:latest
   ports:
     - ${SERVICE_PORT}:80
   volumes:
     - fastapi:/app/api/data

volumes:
  fastapi: