version: '3'

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - "${SERVICE_PORT}:9090"
    volumes:
      - "./data:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
